pipeline {
    agent any
    stages {
        stage("Clean Up"){
            steps{
                deleteDir()
            }
        }
        stage("CLone Repository"){
            steps{
                sh "git clone https://github.com/jenkins-docs/simple-java-maven-app.git"
            }
    }
    stage("build"){
        steps{
            dir("simple-java-maven-app"){
               sh "mvn clean intsall" 
            }
        }
    }
    stage("test"){
        steps{
            dir("simple-java-maven-app"){
               sh "mvn test" 
            }
        }
    }
}
}