pipeline{
    agent any
    parameters{
        booleanParam(defaultValue: false, description: "Go straight?", name: "myBool")
    }
    stages{
        stage("Demo"){
            steps{
                script{
                    if(params.myBool == false){
                        currentBuild.result = "SUCCESS"
                        return
                    }
                    else{
                        echo "booleanParam is set to: TRUE"
                        currentBuild.result = "FAILED"
                    }
                }
            }
        }
    }
}