pipleine{
    agent any
    parameters{
        booleanParam(defaultValue: false, description: "Enable service", name: "myBoolean")
    }
    stages{
        stage("Demo"){

            steps{
                echo "Boolean param is set to: ${params.myBoolean}"
            }

        }
    }
}